// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TestTask.Document.Employee.Database.Context;
using TestTask.Document.Employee.Database.Entities.Enums;

#nullable disable

namespace TestTask.Document.Employee.Database.Migrations
{
    [DbContext(typeof(EmployeeDocumentDbContext))]
    [Migration("20260522143710_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "document_request_status", new[] { "in_process", "processed", "refusal", "sent" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "document_type", new[] { "average_earnings", "other", "personal_income_tax", "work_place_and_seniority" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "employee_position_type", new[] { "accountant", "other" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "employee_type", new[] { "employee" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TestTask.Document.Employee.Database.Entities.DocumentRequestEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AuthorId")
                        .HasColumnType("bigint")
                        .HasColumnName("author_id");

                    b.Property<int>("Count")
                        .HasColumnType("integer")
                        .HasColumnName("count");

                    b.Property<DateTimeOffset>("CreateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_date");

                    b.Property<AccountingDocumentType>("DocumentType")
                        .HasColumnType("document_type")
                        .HasColumnName("document_type");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<RequestStatus>("RequestStatus")
                        .HasColumnType("document_request_status")
                        .HasColumnName("request_status");

                    b.HasKey("Id")
                        .HasName("pk_document_request_id");

                    b.HasIndex("RequestStatus", "DocumentType")
                        .HasDatabaseName("ix_request_status_document_type");

                    b.ToTable("document_requests", (string)null);
                });

            modelBuilder.Entity("TestTask.Document.Employee.Database.Entities.EmployeeEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<EmployeeType>("EmployeeType")
                        .HasColumnType("employee_type")
                        .HasColumnName("employee_type");

                    b.Property<PositionType>("PositionType")
                        .HasColumnType("employee_position_type")
                        .HasColumnName("position_type");

                    b.HasKey("Id")
                        .HasName("pk_employee_id");

                    b.ToTable("employee", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
